name: CI/CD Build, Push to ECR and Deploy ECS

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

  ECR_FRONTEND_REPOSITORY: ${{ vars.ECR_FRONTEND_REPOSITORY }}
  ECR_VENTAS_REPOSITORY: ${{ vars.ECR_VENTAS_REPOSITORY }}
  ECR_DESPACHOS_REPOSITORY: ${{ vars.ECR_DESPACHOS_REPOSITORY }}

  ECS_CLUSTER: proyectosemestral2-cluster
  ECS_SERVICE: app

jobs:
  build-push-and-deploy:
    name: Build, Push and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend image
        run: |
          docker build --platform linux/amd64 \
            -f ./frontend/front_despacho/dockerfile.ecs \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND_REPOSITORY:latest \
            ./frontend/front_despacho

          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND_REPOSITORY:latest

      - name: Build and push backend ventas image
        run: |
          docker build --platform linux/amd64 \
            -f ./backend/back-Ventas_SpringBoot/Springboot-API-REST/dockerfile \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_VENTAS_REPOSITORY:latest \
            ./backend/back-Ventas_SpringBoot/Springboot-API-REST

          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_VENTAS_REPOSITORY:latest

      - name: Build and push backend despachos image
        run: |
          docker build --platform linux/amd64 \
            -f ./backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO/dockerfile \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_DESPACHOS_REPOSITORY:latest \
            ./backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO

          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_DESPACHOS_REPOSITORY:latest

      - name: Force new deployment in ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment